title: BLOG_A
description: In it's right place...
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
permalink: /:categories/:year/:month/:day/:title/

exclude:
  - package.json
  - package-lock.json
  - src/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"